[".config/mpv/scripts/autoload.lua"]
type = "file"
url = "https://raw.githubusercontent.com/mpv-player/mpv/refs/heads/master/TOOLS/lua/autoload.lua"
refreshPeriod = "168h"

[".config/mpv/scripts/memo.lua"]
type = "file"
url = "https://raw.githubusercontent.com/po5/memo/refs/heads/master/memo.lua"
refreshPeriod = "168h"

[".config/mpv/script-opts/memo.conf"]
type = "file"
url = "https://raw.githubusercontent.com/po5/memo/refs/heads/master/memo.conf"
refreshPeriod = "168h"

[".config/mpv/scripts/playlistmanager.lua"]
type = "file"
url = "https://raw.githubusercontent.com/jonniek/mpv-playlistmanager/refs/heads/master/playlistmanager.lua"
refreshPeriod = "168h"

[".config/mpv/script-opts/playlistmanager.conf"]
type = "file"
url = "https://raw.githubusercontent.com/jonniek/mpv-playlistmanager/refs/heads/master/playlistmanager.conf"
refreshPeriod = "168h"

[".config/mpv/scripts/osc.lua"]
type = "file"
url = "https://raw.githubusercontent.com/po5/thumbfast/refs/heads/vanilla-osc/player/lua/osc.lua"
refreshPeriod = "168h"

[".config/mpv/scripts/thumbfast.lua"]
type = "file"
url = "https://raw.githubusercontent.com/po5/thumbfast/refs/heads/master/thumbfast.lua"
refreshPeriod = "168h"

[".config/mpv/script-opts/thumbfast.conf"]
type = "file"
url = "https://raw.githubusercontent.com/po5/thumbfast/refs/heads/master/thumbfast.conf"
refreshPeriod = "168h"

[".config/bat/themes/Catppuccin Latte.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Latte.tmTheme"
refreshPeriod = "168h"
