import = [
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/tokyonight/tokyonight_storm.toml"
]

[window]
padding = { x = 20, y = 20 }
option_as_alt = "OnlyLeft"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16.0
builtin_box_drawing = false

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }

[keyboard]
bindings = [
  { key = "U", mods = "Command", mode = "~Vi|~Search", action = "ScrollPageUp" },
  { key = "D", mods = "Command", mode = "~Vi|~Search", action = "ScrollPageDown" },
]
